More fixes and cleanups

diff --git a/mvn-get b/mvn-get
--- a/mvn-get
+++ b/mvn-get
@@ -26,7 +26,7 @@ download()
 	local URL="${1}"
 	local AUTH="${2:-""}"
 	local DEST="${3:-""}"
-	[ -n "${AUTH}" ] && AUTH="--user '${AUTH}'"
+	[ -n "${AUTH}" ] && AUTH="--user ${AUTH}"
 	[ -n "${DEST}" ] && DEST=(--output "${DEST}")
 	"${CURL}" --location --fail --disallow-username-in-url --config <(echo -n "${AUTH}") "${DEST[@]}" "${URL}"
 }
@@ -109,9 +109,9 @@ for n in "${@}" ; do
 	FINAL_VERSION="${VERSION}"
 	if [[ "${VERSION}" =~ -SNAPSHOT$ ]] ; then
 		say "⚠️ This version is a snapshot - identifying the final artifact to download"
-		POM="$(download "${BASE}/maven-metadata.xml" "${AUTH}" 2>/dev/null)" || fail "Failed to download the artifact metadata for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION}"
-		TIMESTAMP="$("${XMLSTARLET}" sel -t -v '/metadata/versioning/snapshot/timestamp' <<< "${POM}")"
-		BUILD_NUMBER="$("${XMLSTARLET}" sel -t -v '/metadata/versioning/snapshot/buildNumber' <<< "${POM}")"
+		XML="$(download "${BASE}/maven-metadata.xml" "${AUTH}" 2>/dev/null)" || fail "Failed to download the artifact metadata for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION} from [${BASE}/maven-metadata.xml]"
+		TIMESTAMP="$("${XMLSTARLET}" sel -t -v '/metadata/versioning/snapshot/timestamp' <<< "${XML}")"
+		BUILD_NUMBER="$("${XMLSTARLET}" sel -t -v '/metadata/versioning/snapshot/buildNumber' <<< "${XML}")"
 		FINAL_VERSION="$(echo -n "${VERSION}" | sed -e "s/-SNAPSHOT$/-${TIMESTAMP}-${BUILD_NUMBER}/g")"
 		say "\t✅ The latest snapshot version is ${FINAL_VERSION}"
 	fi
@@ -119,7 +119,7 @@ for n in "${@}" ; do
 	BASE="${BASE}/${ARTIFACT_ID}-${FINAL_VERSION}"
 	if [ -z "${EXTENSION}" ] ; then
 		say "⚠️ Packaging (type) not provided, must identify it from the POM"
-		POM="$(download "${BASE}.pom" "${AUTH}" 2>/dev/null)" || fail "Failed to download the artifact POM for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION}"
+		POM="$(download "${BASE}.pom" "${AUTH}" 2>/dev/null)" || fail "Failed to download the artifact POM for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION} from [${BASE}.pom]"
 		EXTENSION="$("${XMLSTARLET}" sel -N "p=http://maven.apache.org/POM/4.0.0" -t -v '/p:project/p:packaging' <<< "${POM}")"
 		[ -z "${EXTENSION}" ] && EXTENSION="jar"
 		say "\t✅ Will download the ${EXTENSION} artifact"
