Major rework for simplification

diff --git a/mvn-get b/mvn-get
--- a/mvn-get
+++ b/mvn-get
@@ -2,26 +2,40 @@
 
 set -euo pipefail
 
-timestamp() {
+timestamp()
+{
 	/usr/bin/date -Ins -u
 }
 
-say() {
+say()
+{
 	echo -e "$(timestamp): ${@}"
 }
 
-fail() {
+fail()
+{
 	say "❌ ${@}" 1>&2
 	exit ${EXIT_CODE:-1}
 }
 
-cleanup() {
-	if [ -v WORK_DIR ] ; then
-		[ -d "${WORK_DIR}" ] && /usr/bin/rm -rf "${WORK_DIR}" &>/dev/null
-	fi
+download()
+{
+	local URL="${1}"
+	local AUTH="${2:-""}"
+	local DEST="${3:-""}"
+	[ -n "${AUTH}" ] && AUTH="--user '${AUTH}'"
+	[ -n "${DEST}" ] && DEST=(--output "${DEST}")
+	"${CURL}" --location --fail --disallow-username-in-url --config <(echo -n "${AUTH}") "${DEST[@]}" "${URL}"
 }
 
-usage() {
+get_repo_auth()
+{
+	local URL="${1}"
+	# TODO: How to fetch this?
+}
+
+usage()
+{
 	{
 		echo -e "usage: ${BASH_SOURCE:-${0}} spec1 [spec2 spec3 ... specN]"
 		echo -e ""
@@ -37,15 +51,8 @@ usage() {
 
 [ ${#} -ge 1 ] || usage
 
-MVN="$(type -P mvn)" || fail "Maven is not in the path"
-
-WORK_DIR="$(/usr/bin/mktemp -d -p "${PWD}" ".mvn-tmp.XXXXXX")" || fail "Failed to create the temporary work directory"
-trap cleanup EXIT
-
-M2_DIR="${WORK_DIR}/m2"
-INT_DIR="${WORK_DIR}/int"
-
-LOCAL=(-Dmaven.repo.local="${M2_DIR}")
+XMLSTARLET="$(type -P xmlstarlet)" || fail "xmlstarlet is not installed - cannot proceed"
+CURL="$(type -P curl)" || fail "curl is not installed - cannot proceed"
 
 # Each parameter is of the form artifact[@repo]=target
 for n in "${@}" ; do
@@ -53,66 +60,47 @@ for n in "${@}" ; do
 
 	[[ "${n}" =~ ^([^@=[:space:]]+)(@([^=[:space:]]*))?=(.+)$ ]] || fail "Artifact spec [${n}] is not valid"
 	ARTIFACT="${BASH_REMATCH[1]}"
-	REPOSITORY="${BASH_REMATCH[3]}"
+	REPO_URL="${BASH_REMATCH[3]}"
 	DEST="${BASH_REMATCH[4]}"
 
 	[[ "${ARTIFACT}" =~ ^([^:[:space:]]+):([^:[:space:]]+):([^:[:space:]]+)(:([^:[:space:]]+)(:([^:[:space:]]+))?)?$ ]] || fail "The artifact string [${ARTIFACT}] is not valid"
 	GROUP_ID="${BASH_REMATCH[1]}"
 	ARTIFACT_ID="${BASH_REMATCH[2]}"
 	VERSION="${BASH_REMATCH[3]}"
-	PACKAGING="${BASH_REMATCH[5]}"
+	EXTENSION="${BASH_REMATCH[5]}"
 	CLASSIFIER="${BASH_REMATCH[7]}"
 
-	REPO=()
-	REPO_MSG=""
-	if [ -n "${REPOSITORY}" ] ; then
-		REPO=(-DremoteRepositories="${REPOSITORY}")
-		REPO_MSG=" from repository [${REPOSITORY}]"
+	AUTH="$(get_repo_auth "${REPO_URL}")"
+
+	GROUP_PATH="${GROUP_ID//./\/}"
+	BASE="${REPO_URL}/${GROUP_PATH}/${ARTIFACT_ID}/${VERSION}"
+
+	say "👉 Downloading:"
+	say "\tArtifact:   [${ARTIFACT}]"
+	say "\tRepository: [${REPO_URL}]"
+	say "\tFile:       [${DEST}]"
+
+	FINAL_VERSION="${VERSION}"
+	if [[ "${VERSION}" =~ -SNAPSHOT$ ]] ; then
+		say "⚠️ This version is a snapshot - identifying the final artifact to download"
+		POM="$(download "${BASE}/maven-metadata.xml" "${AUTH}" 2>/dev/null)" || fail "Failed to download the artifact metadata for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION}"
+		TIMESTAMP="$("${XMLSTARLET}" sel -t -v '/metadata/versioning/snapshot/timestamp' <<< "${POM}")"
+		BUILD_NUMBER="$("${XMLSTARLET}" sel -t -v '/metadata/versioning/snapshot/buildNumber' <<< "${POM}")"
+		FINAL_VERSION="$(echo -n "${VERSION}" | sed -e "s/-SNAPSHOT$/-${TIMESTAMP}-${BUILD_NUMBER}/g")"
+		say "✅ The latest snapshot version is ${FINAL_VERSION}"
 	fi
 
-	say "👉 Downloading [${ARTIFACT}]${REPO_MSG}"
-	say "\tGroupId:    ${GROUP_ID}"
-	say "\tArtifactId: ${ARTIFACT_ID}"
-	say "\tVersion:    ${VERSION}"
-	[ -z "${PACKAGING}" ] || say "\tPackaging:  ${PACKAGING}"
-	[ -z "${CLASSIFIER}" ] || say "\tClassifier: ${CLASSIFIER}"
-
-	"${MVN}" -e -q -U "${LOCAL[@]}" dependency:get -Dartifact="${ARTIFACT}" "${REPO[@]}" -Dtransitive=false || fail "Failed to download [${ARTIFACT}]${REPO_MSG}"
-	say "\t✅ Download complete!"
-
-	ARTIFACT_PATH="${GROUP_ID//.//}/${ARTIFACT_ID}/${VERSION}"
-	say "👉 Removing remote repository references from [${M2_DIR}]..."
-	/usr/bin/find "${ARTIFACT_PATH}" -name "_remote.repositories" -exec /usr/bin/rm -f '{}' ';' || true
-
-	say "👉 Copying [${ARTIFACT}] into its final location at [${DEST}]..."
-	"${MVN}" -q "${LOCAL[@]}" dependency:copy -Dartifact="${ARTIFACT}" -DoutputDirectory="${INT_DIR}" -Dmdep.stripClassifier=true -Dmdep.stripVersion=true -Dmdep.useBaseVersion=true -DoutputAbsoluteArtifactFilename=true || (
-		set -euo pipefail
-		say "\t⚠️ Maven Copy failed - will try a manual copy"
-		FILE="$(/usr/bin/find "${M2_DIR}/${ARTIFACT_PATH}" -type f -name "${ARTIFACT_ID}-${VERSION}*" -not -name "*.lastUpdated" -not -name "*.sha1" -not -name "*.pom")"
-		[ -n "${FILE}" ] && [ -e "${FILE}" ] || exit 1
-		/usr/bin/cp -f "${FILE}" "${INT_DIR}"
-		say "\t✅ Manual copy succeeded!"
-	) || fail "Failed to copy [${ARTIFACT}] into the work directory"
-
-	SRC_FILE="$(/usr/bin/find "${INT_DIR}" -type f | /usr/bin/sort | /usr/bin/head -1)"
-	SRC_FILE_NAME="${SRC_FILE##*/}"
-	say "\t👉 Intermediate copy... (${SRC_FILE_NAME})"
-
-	DEST_DIR="$(/usr/bin/dirname "${DEST}")"
-	DEST_NAME="$(/usr/bin/basename "${DEST}")"
-	[ -d "${DEST_DIR}" ] || mkdir -p "${DEST_DIR}" &>/dev/null || fail "Failed to create the destination directory [${DEST_DIR}]"
-	DEST_DIR="$(/usr/bin/readlink -f "${DEST_DIR}")"
-
-	DEST="${DEST_DIR}/${DEST_NAME}"
-
-	# If the destination already exists, then ... if it's a directory, we must append the artifact's filename
-	# if it's a file, we use the filename as-is
-	if [ -e "${DEST}" ] ; then
-		[ -d "${DEST}" ] && DEST+="/${SRC_FILE_NAME}"
+	BASE="${BASE}/${ARTIFACT_ID}-${FINAL_VERSION}"
+	if [ -z "${EXTENSION}" ] ; then
+		say "⚠️ Packaging (type) not provided, must identify it from the POM"
+		POM="$(download "${BASE}.pom" "${AUTH}" 2>/dev/null)" || fail "Failed to download the artifact POM for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION}"
+		EXTENSION="$("${XMLSTARLET}" sel -N "p=http://maven.apache.org/POM/4.0.0" -t -v '/p:project/p:packaging' <<< "${POM}")"
+		[ -z "${EXTENSION}" ] && EXTENSION="jar"
+		say "✅ Will download the ${EXTENSION} artifact"
 	fi
 
-	/usr/bin/mv -f "${SRC_FILE}" "${DEST}" || fail "Failed to copy [${ARTIFACT}] into [${DEST}]"
-	say "\t👉 Rendering helpers..."
-	/usr/local/bin/render-helpers "${DEST}" "${VERSION}" || fail "Failed to render the helpers for [${DEST}]"
-	say "\t✅ Copy complete! Final file: [${DEST}]"
+	# Must be given explicitly ...
+	[ -n "${CLASSIFIER}" ] && CLASSIFIER="-${CLASSIFIER}"
+
+	download "${BASE}${CLASSIFIER}.${EXTENSION}" "${AUTH}" "${DEST}"
 done
