Fix many edge errors regarding XML parsing

diff --git a/mvn-get b/mvn-get
--- a/mvn-get
+++ b/mvn-get
@@ -91,6 +91,7 @@ CLASSIFIER="${BASH_REMATCH[8]}"
 [ -n "${VERSION}" ] || VERSION="RELEASE"
 
 XMLSTARLET="$(type -P xmlstarlet)" || fail "xmlstarlet is not installed - cannot proceed"
+XMLLINT="$(type -P xmllint)" || fail "xmllint is not installed - cannot proceed"
 CURL="$(type -P curl)" || fail "curl is not installed - cannot proceed"
 
 NEED_DECRYPT="true"
@@ -121,7 +122,7 @@ if [ -v MVN_GET_USERNAME ] && [ -v MVN_GET_PASSWORD ] ; then
 	AUTH="${MVN_GET_USERNAME}:${MVN_GET_PASSWORD}"
 fi
 
-[[ "${REPO_URL,,}" =~ ^https?:// ]] || fail "Repository [${REPO_URL}] from artifact parameter [${n}] is not valid"
+[[ "${REPO_URL,,}" =~ ^https?:// ]] || fail "Repository [${REPO_URL}] from artifact parameter [${ARTIFACT}] is not valid"
 
 GROUP_PATH="${GROUP_ID//./\/}"
 BASE="${REPO_URL}/${GROUP_PATH}/${ARTIFACT_ID}"
@@ -139,7 +140,8 @@ if [ "${VERSION}" == "LATEST" ] || [ "${VERSION}" == "RELEASE" ] ; then
 	[ "${VERSION}" == "RELEASE" ] && SUPPORT_SNAPSHOT="false"
 	say "⚠️ Identifying the ${VERSION} artifact version to download..."
 	XML="$(download "${BASE}/maven-metadata.xml" "${AUTH}" 2>/dev/null)" || fail "Failed to download the artifact metadata for ${GROUP_ID}:${ARTIFACT_ID} from [${BASE}/maven-metadata.xml]"
-	FINAL_VERSION="$("${XMLSTARLET}" sel -t -v "/metadata/versioning/${VERSION,,}" <<< "${XML}")"
+	"${XMLLINT}" - <<< "${XML}" &>/dev/null || fail "The artifact metadata for ${GROUP_ID}:${ARTIFACT_ID} downloaded from [${BASE}/maven-metadata.xml] is not valid XML"
+	FINAL_VERSION="$("${XMLSTARLET}" sel -t -v "/metadata/versioning/${VERSION,,}" <<< "${XML}")" || fail "Failed to identify the ${VERSION} version for ${GROUP_ID}:${ARTIFACT_ID} from the XML at [${BASE}/maven-metadata.xml]"
 	say "\t✅ The ${VERSION} version is ${FINAL_VERSION}"
 	VERSION="${FINAL_VERSION}"
 fi
@@ -149,9 +151,10 @@ BASE+="/${VERSION}"
 if "${SUPPORT_SNAPSHOT}" && [[ "${VERSION}" =~ -SNAPSHOT$ ]] ; then
 	say "⚠️ This version is a SNAPSHOT - identifying the final artifact to download"
 	XML="$(download "${BASE}/maven-metadata.xml" "${AUTH}" 2>/dev/null)" || fail "Failed to download the artifact metadata for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION} from [${BASE}/maven-metadata.xml]"
-	TIMESTAMP="$("${XMLSTARLET}" sel -t -v '/metadata/versioning/snapshot/timestamp' <<< "${XML}")"
-	BUILD_NUMBER="$("${XMLSTARLET}" sel -t -v '/metadata/versioning/snapshot/buildNumber' <<< "${XML}")"
-	FINAL_VERSION="$(echo -n "${VERSION}" | sed -e "s/-SNAPSHOT$/-${TIMESTAMP}-${BUILD_NUMBER}/g")"
+	"${XMLLINT}" - <<< "${XML}" &>/dev/null || fail "The artifact metadata for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION} downloaded from [${BASE}/maven-metadata.xml] is not valid XML"
+	TIMESTAMP="$("${XMLSTARLET}" sel -t -v '/metadata/versioning/snapshot/timestamp' <<< "${XML}")" || fail "No timestamp data is present for the required snapshot version, cannot continue"
+	BUILD_NUMBER="$("${XMLSTARLET}" sel -t -v '/metadata/versioning/snapshot/buildNumber' <<< "${XML}")" || fail "No build number data is present for the required snapshot version, cannot continue"
+	FINAL_VERSION="$(echo -n "${VERSION}" | /usr/bin/sed -e "s/-SNAPSHOT$/-${TIMESTAMP}-${BUILD_NUMBER}/g")"
 	say "\t✅ The latest SNAPSHOT version is ${FINAL_VERSION}"
 fi
 
@@ -160,7 +163,8 @@ TAB=""
 if [ -z "${EXTENSION}" ] ; then
 	say "⚠️ Packaging (type) not provided, must identify it from the POM"
 	POM="$(download "${BASE}.pom" "${AUTH}" 2>/dev/null)" || fail "Failed to download the artifact POM for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION} from [${BASE}.pom]"
-	EXTENSION="$("${XMLSTARLET}" sel -N "p=http://maven.apache.org/POM/4.0.0" -t -v '/p:project/p:packaging' <<< "${POM}")"
+	"${XMLLINT}" - <<< "${POM}" &>/dev/null || fail "The artifact POM for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION} downloaded from [${BASE}.pom] is not valid XML"
+	EXTENSION="$("${XMLSTARLET}" sel -N "p=http://maven.apache.org/POM/4.0.0" -t -v '/p:project/p:packaging' <<< "${POM}")" || true
 	[ -z "${EXTENSION}" ] && EXTENSION="jar"
 	TAB="\t"
 fi
