Support LATEST and RELEASE version tags
Also allow artifacts to be fetched without version specification, which will default to LATEST

diff --git a/mvn-get b/mvn-get
--- a/mvn-get
+++ b/mvn-get
@@ -80,12 +80,14 @@ for n in "${@}" ; do
 	REPO_URL="${BASH_REMATCH[3]}"
 	DEST="${BASH_REMATCH[4]}"
 
-	[[ "${ARTIFACT}" =~ ^([^:[:space:]]+):([^:[:space:]]+):([^:[:space:]]+)(:([^:[:space:]]+)(:([^:[:space:]]+))?)?$ ]] || fail "The artifact string [${ARTIFACT}] is not valid"
+	[[ "${ARTIFACT}" =~ ^([^:[:space:]]+):([^:[:space:]]+)(:([^:[:space:]]+)?(:([^:[:space:]]+)?(:([^:[:space:]]+)?)?)?)?$ ]] || fail "The artifact string [${ARTIFACT}] is not valid"
 	GROUP_ID="${BASH_REMATCH[1]}"
 	ARTIFACT_ID="${BASH_REMATCH[2]}"
-	VERSION="${BASH_REMATCH[3]}"
-	EXTENSION="${BASH_REMATCH[5]}"
-	CLASSIFIER="${BASH_REMATCH[7]}"
+	VERSION="${BASH_REMATCH[4]}"
+	EXTENSION="${BASH_REMATCH[6]}"
+	CLASSIFIER="${BASH_REMATCH[8]}"
+
+	[ -n "${VERSION}" ] || VERSION="LATEST"
 
 	if [[ "${REPO_URL,,}" =~ ^[a-zA-Z0-9][-/._a-zA-Z0-9]*$ ]] ; then
 		read USERPW64 REAL_URL REST < <(get_repo_auth "${REPO_URL}") || true
@@ -99,7 +101,7 @@ for n in "${@}" ; do
 	fi
 
 	GROUP_PATH="${GROUP_ID//./\/}"
-	BASE="${REPO_URL}/${GROUP_PATH}/${ARTIFACT_ID}/${VERSION}"
+	BASE="${REPO_URL}/${GROUP_PATH}/${ARTIFACT_ID}"
 
 	say "👉 Downloading:"
 	say "\tArtifact:    [${ARTIFACT}]"
@@ -107,26 +109,45 @@ for n in "${@}" ; do
 	say "\tDestination: [${DEST}]"
 
 	FINAL_VERSION="${VERSION}"
-	if [[ "${VERSION}" =~ -SNAPSHOT$ ]] ; then
-		say "⚠️ This version is a snapshot - identifying the final artifact to download"
+	SUPPORT_SNAPSHOT="true"
+	if [ "${VERSION}" == "LATEST" ] || [ "${VERSION}" == "RELEASE" ] ; then
+		# This shouldn't be necessary, as the metadata should never reference SNAPSHOTS
+		# in the <release> element, but we take precautions nonetheless
+		[ "${VERSION}" == "RELEASE" ] && SUPPORT_SNAPSHOT="false"
+		say "⚠️ Identifying the ${VERSION} artifact version to download..."
+		XML="$(download "${BASE}/maven-metadata.xml" "${AUTH}" 2>/dev/null)" || fail "Failed to download the artifact metadata for ${GROUP_ID}:${ARTIFACT_ID} from [${BASE}/maven-metadata.xml]"
+		FINAL_VERSION="$("${XMLSTARLET}" sel -t -v "/metadata/versioning/${VERSION,,}" <<< "${XML}")"
+		say "\t✅ The ${VERSION} version is ${FINAL_VERSION}"
+		VERSION="${FINAL_VERSION}"
+	fi
+
+	# If the final version is a snapshot, then we must resolve that
+	BASE+="/${VERSION}"
+	if "${SUPPORT_SNAPSHOT}" && [[ "${VERSION}" =~ -SNAPSHOT$ ]] ; then
+		say "⚠️ This version is a SNAPSHOT - identifying the final artifact to download"
 		XML="$(download "${BASE}/maven-metadata.xml" "${AUTH}" 2>/dev/null)" || fail "Failed to download the artifact metadata for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION} from [${BASE}/maven-metadata.xml]"
 		TIMESTAMP="$("${XMLSTARLET}" sel -t -v '/metadata/versioning/snapshot/timestamp' <<< "${XML}")"
 		BUILD_NUMBER="$("${XMLSTARLET}" sel -t -v '/metadata/versioning/snapshot/buildNumber' <<< "${XML}")"
 		FINAL_VERSION="$(echo -n "${VERSION}" | sed -e "s/-SNAPSHOT$/-${TIMESTAMP}-${BUILD_NUMBER}/g")"
-		say "\t✅ The latest snapshot version is ${FINAL_VERSION}"
+		say "\t✅ The latest SNAPSHOT version is ${FINAL_VERSION}"
 	fi
 
 	BASE="${BASE}/${ARTIFACT_ID}-${FINAL_VERSION}"
+	TAB=""
 	if [ -z "${EXTENSION}" ] ; then
 		say "⚠️ Packaging (type) not provided, must identify it from the POM"
 		POM="$(download "${BASE}.pom" "${AUTH}" 2>/dev/null)" || fail "Failed to download the artifact POM for ${GROUP_ID}:${ARTIFACT_ID}:${VERSION} from [${BASE}.pom]"
 		EXTENSION="$("${XMLSTARLET}" sel -N "p=http://maven.apache.org/POM/4.0.0" -t -v '/p:project/p:packaging' <<< "${POM}")"
 		[ -z "${EXTENSION}" ] && EXTENSION="jar"
-		say "\t✅ Will download the ${EXTENSION} artifact"
+		TAB="\t"
 	fi
+	say "${TAB}✅ Will download the ${EXTENSION} artifact"
 
 	# Must be given explicitly ...
-	[ -n "${CLASSIFIER}" ] && CLASSIFIER="-${CLASSIFIER}"
+	if [ -n "${CLASSIFIER}" ] ; then
+		CLASSIFIER="-${CLASSIFIER}"
+		say "✅ The classifier is ${CLASSIFIER}"
+	fi
 
 	download "${BASE}${CLASSIFIER}.${EXTENSION}" "${AUTH}" "${DEST}"
 done
