Added safeguards to avoid races and ensure data integrity

diff --git a/scripts/global-sums b/scripts/global-sums
--- a/scripts/global-sums
+++ b/scripts/global-sums
@@ -3,6 +3,11 @@
 set -euo pipefail
 . /.functions
 
+set_or_default BASE_DIR "/app"
+set_or_default FILE_DIR "${BASE_DIR}/file"
+set_or_default RENDER_LOCK "/.render-lock"
+set_or_default LOCK_TIMEOUT "5m"
+
 get_category_sums()
 {
 	local CATEGORY="${1}"
@@ -14,20 +19,46 @@ get_category_sums()
 	done
 }
 
-#
-# Generate the GLOBAL_SUMS value
-#
-GLOBAL_SUMS=""
-while read CATEGORY ; do
-	SUMS=()
-	while read ARTIFACT ; do
-		[ -f "${ARTIFACT}.sum" ] || fail "No checksum computed for [${ARTIFACT}] ... initialization failed"
-		SUMS+=( "${ARTIFACT}.sum" )
-	done < <(find "${CATEGORY}" -type f -not -name '*.sum' -not -name '*.ver' | sort)
-	if [ ${#SUMS[@]} -gt 0 ] ; then
-		read SUM REST < <(get_category_sums "${CATEGORY}" "${SUMS[@]}" | sha256sum)
-		[ -n "${GLOBAL_SUMS}" ] && GLOBAL_SUMS+=", "
-		GLOBAL_SUMS+="\"${CATEGORY##*/}\": \"${SUM}\""
-	fi
-done < <(find "${FILE_DIR}" -mindepth 1 -maxdepth 1 -type d | sort)
-exec jq -r <<< "{${GLOBAL_SUMS}}"
+LOCK_TIMEOUT_SECS="$(timestr_to_secs "${LOCK_TIMEOUT}")" || fail "Invalid syntax for the lock timeout [${LOCK_TIMEOUT}]"
+
+FIRST="true"
+START="$(date +%s)"
+while true ; do
+	is_file "${RENDER_LOCK}" && break
+	as_boolean "${FIRST}" && sleeping "Waiting for the rendering lock to appear"
+	FIRST="false"
+	sleep 1 || fail "Sleep interrupted!"
+	NOW="$(date +%s)"
+	[ $(( NOW - START )) -ge ${LOCK_TIMEOUT_SECS} ] && break
+done
+is_file "${RENDER_LOCK}" || fail "The rendering lock was not created in time"
+
+eyes "Rendering lock ready!"
+
+{
+	flock --shared --wait ${LOCK_TIMEOUT_SECS} 999 || fail "Failed to acquire a read lock on the rendering lock"
+
+	ACTUAL="$(<"${RENDER_LOCK}")"
+	read EXPECTED REST < <(find "${FILE_DIR}" -mindepth 2 -type f -name '*.sum' | sort | xargs cat | sha256sum)
+
+	[ "${EXPECTED}" == "${ACTUAL}" ] || fail "Render Lock Data mismatch: expected [${EXPECTED}] but got [${ACTUAL}]"
+
+	#
+	# Generate the GLOBAL_SUMS value
+	#
+	GLOBAL_SUMS=""
+	while read CATEGORY ; do
+		SUMS=()
+		while read ARTIFACT ; do
+			[ -f "${ARTIFACT}.sum" ] || fail "No checksum computed for [${ARTIFACT}] ... initialization failed"
+			SUMS+=( "${ARTIFACT}.sum" )
+		done < <(find "${CATEGORY}" -type f -not -name '*.sum' -not -name '*.ver' | sort)
+		if [ ${#SUMS[@]} -gt 0 ] ; then
+			read SUM REST < <(get_category_sums "${CATEGORY}" "${SUMS[@]}" | sha256sum)
+			[ -n "${GLOBAL_SUMS}" ] && GLOBAL_SUMS+=", "
+			GLOBAL_SUMS+="\"${CATEGORY##*/}\": \"${SUM}\""
+		fi
+	done < <(find "${FILE_DIR}" -mindepth 1 -maxdepth 1 -type d | sort)
+	exec jq -r <<< "{${GLOBAL_SUMS}}"
+
+} 999<"${RENDER_LOCK}"
diff --git a/scripts/rebuild-helpers b/scripts/rebuild-helpers
--- a/scripts/rebuild-helpers
+++ b/scripts/rebuild-helpers
@@ -5,33 +5,43 @@ set -euo pipefail
 
 set_or_default BASE_DIR "/app"
 set_or_default FILE_DIR "${BASE_DIR}/file"
+set_or_default RENDER_LOCK "/.render-lock"
 
-doing "Cleaning out old checksum files..."
-find "${FILE_DIR}" -type f -name '*.sum' -delete
+:> "${RENDER_LOCK}" || fail "Failed to create the rendering lock"
+{
+	flock --exclusive --nonblock 999 || fail "The rendering lock is currently being held, cannot continue"
 
-doing "Rendering any missing helpers for all contents of [${FILE_DIR}]..."
-COUNT=0
-FAILED=()
-while read FILE ; do
-	say "\t👉 Processing [${FILE}]..."
-	VER=""
-	[ -s "${FILE}.ver" ] && VER="$(<"${FILE}.ver")"
-	if render-helpers "${FILE}" "${VER}" ; then
-		(( ++COUNT ))
-	else
-		FAILED+=("${FILE}")
-	fi |& sed -e 's;^;\t\t;g'
-done < <(find "${FILE_DIR}" -type f -not -name '*.sum' -not -name '*.ver' | sort)
+	doing "Cleaning out old checksum files..."
+	find "${FILE_DIR}" -type f -name '*.sum' -delete
 
-if [ ${#FAILED[@]} -gt 0 ] ; then
+	doing "Rendering any missing helpers for all contents of [${FILE_DIR}]..."
+	COUNT=0
+	FAILED=()
+	while read FILE ; do
+		say "\t👉 Processing [${FILE}]..."
+		VER=""
+		[ -s "${FILE}.ver" ] && VER="$(<"${FILE}.ver")"
+		if render-helpers "${FILE}" "${VER}" ; then
+			(( ++COUNT ))
+		else
+			FAILED+=("${FILE}")
+		fi |& sed -e 's;^;\t\t;g'
+	done < <(find "${FILE_DIR}" -mindepth 2 -type f -not -name '*.sum' -not -name '*.ver' | sort)
+
+	if [ ${#FAILED[@]} -gt 0 ] ; then
+		S="s"
+		[ ${#FAILED[@]} -ne 1 ] || S=""
+		say "Rendering failed for the following ${#FAILED[@]} file${S}:"
+		for FILE in "${FAILED[@]}" ; do
+			say "\t${FILE}"
+		done
+		fail "Rebuilding helpers failed"
+	fi
 	S="s"
-	[ ${#FAILED[@]} -ne 1 ] || S=""
-	say "Rendering failed for the following ${#FAILED[@]} file${S}:"
-	for FILE in "${FAILED[@]}" ; do
-		say "\t${FILE}"
-	done
-	fail "Rebuilding helpers failed"
-fi
-S="s"
-[ ${COUNT} -ne 1 ] || S=""
-ok "Rendered artifact helpers (version + checksum) for ${COUNT} element${S}"
+	[ ${COUNT} -ne 1 ] || S=""
+	ok "Rendered artifact helpers (version + checksum) for ${COUNT} element${S}"
+
+	# This just allows the other ones to verify that the lock is, indeed, complete
+	read LOCK_DATA REST < <(find "${FILE_DIR}" -mindepth 2 -type f -name '*.sum' | sort | xargs cat | sha256sum)
+	echo -n "${LOCK_DATA}" > "${RENDER_LOCK}"
+} 999<"${RENDER_LOCK}"
